# Clase 14C — Mini ChatGPT con RAG usando el dataset real del curso
**Autor:** Josef Rodríguez

Esta clase integra todo lo aprendido:

- chunking
- embeddings
- vector search
- construcción de contexto
- respuesta con modelo generativo

Dataset utilizado:

`https://raw.githubusercontent.com/josefrodrim/ML-course/main/data/planes_gobierno_texto.csv`

# 1. Objetivo de la clase

Construir un sistema estilo **mini ChatGPT con RAG** sobre planes de gobierno.

## Flujo final

```text
Dataset real
   ↓
Chunking
   ↓
Embeddings
   ↓
Índice vectorial
   ↓
Consulta del usuario
   ↓
Top-K chunks
   ↓
Prompt
   ↓
LLM
   ↓
Respuesta
```

# 2. Cargar datos y preparar chunks

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/josefrodrim/ML-course/main/data/planes_gobierno_texto.csv"
df = pd.read_csv(url)
df = df.rename(columns={df.columns[0]: "presidente", df.columns[1]: "texto_plan"})
df["texto_plan"] = df["texto_plan"].fillna("").astype(str)

df.head()

,presidente,texto_plan
0,PABLO ALFONSO LOPEZ CHAU NAVA,formato del resumen del plan de gobierno el fo...
1,RONALD DARWIN ATENCIO SOTOMAYOR,formato del resumen del plan de gobierno el fo...
2,CESAR ACUÑA PERALTA,formato del resumen del plan de gobierno el fo...
3,JOSE DANIEL WILLIAMS ZAPATA,formato del resumen del plan de gobierno el fo...
4,ALVARO GONZALO PAZ DE LA BARRA FREIGEIRO,formato del resumen del plan de gobierno el fo...

In [2]:
def chunk_text(text, chunk_size=180, overlap=40):
    words = text.split()
    chunks = []
    step = max(chunk_size - overlap, 1)
    for i in range(0, len(words), step):
        part = words[i:i+chunk_size]
        if not part:
            continue
        chunks.append(" ".join(part))
        if i + chunk_size >= len(words):
            break
    return chunks

rows = []
for _, row in df.iterrows():
    chunks = chunk_text(row["texto_plan"], chunk_size=180, overlap=40)
    for j, ch in enumerate(chunks):
        rows.append({
            "presidente": row["presidente"],
            "chunk_id": j,
            "chunk_text": ch
        })

chunks_df = pd.DataFrame(rows)
chunks_df.head()

,presidente,chunk_id,chunk_text
0,PABLO ALFONSO LOPEZ CHAU NAVA,0,formato del resumen del plan de gobierno el fo...
1,PABLO ALFONSO LOPEZ CHAU NAVA,1,de dichos objetivos. problemas objetivos indic...
2,PABLO ALFONSO LOPEZ CHAU NAVA,2,reciba la atención que necesita en el momento ...
3,PABLO ALFONSO LOPEZ CHAU NAVA,3,"salud y/o remodelados y oportunos, puestos en ..."
4,PABLO ALFONSO LOPEZ CHAU NAVA,4,de afectan la salud de vacunación en menores s...

# 3. Embeddings e índice vectorial

In [3]:
# Si estás en un entorno limpio, descomenta:
# !pip install -q sentence-transformers faiss-cpu transformers accelerate sentencepiece

In [4]:
from sentence_transformers import SentenceTransformer
import numpy as np
import faiss

embed_model = SentenceTransformer("all-MiniLM-L6-v2")

chunk_embeddings = embed_model.encode(
    chunks_df["chunk_text"].tolist(),
    show_progress_bar=True
)
chunk_embeddings = np.array(chunk_embeddings).astype("float32")

dimension = chunk_embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(chunk_embeddings)

index.ntotal

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/28 [00:00<?, ?it/s]

881

# 4. Retriever

In [5]:
def retrieve_chunks(query, top_k=5):
    q_emb = embed_model.encode([query]).astype("float32")
    distances, indices = index.search(q_emb, top_k)
    out = chunks_df.iloc[indices[0]].copy()
    out["distance_l2"] = distances[0]
    return out[["presidente", "chunk_id", "chunk_text", "distance_l2"]]

retrieve_chunks("propuestas sobre educación pública", top_k=5)

,presidente,chunk_id,chunk_text,distance_l2
515,VLADIMIR ROY CERRON ROJAS,23,de 16. • incrementar desigual y limitado unive...,0.747294
532,VLADIMIR ROY CERRON ROJAS,40,"programas de territorios, lo que públicas arti...",0.761905
572,VLADIMIR ROY CERRON ROJAS,80,de 11. • incorporar educación y cultura ciudad...,0.786557
675,MARIA SOLEDAD PEREZ TELLO DE RODRIGUEZ,24,"asociación (social, % de jóvenes 15-29 al comu...",0.790544
200,ROBERTO HELBERT SANCHEZ PALOMINO,13,con programa nacional ¿ # de jóvenes públicas....,0.797957

# 5. Prompt builder

En un sistema RAG serio, el prompt debe:

1. delimitar el contexto,
2. restringir la respuesta a la evidencia,
3. dejar explícito qué hacer si no hay soporte.

In [6]:
def build_prompt(query, retrieved_df):
    context = "\n\n".join(
        [f"[{r.presidente} | chunk {r.chunk_id}] {r.chunk_text}" for r in retrieved_df.itertuples()]
    )
    prompt = f"""Eres un asistente analítico que responde preguntas sobre planes de gobierno presidenciales.
Usa únicamente el contexto proporcionado.
Si la respuesta no se encuentra claramente en el contexto, responde: "No lo sé con la evidencia recuperada".

Contexto:
{context}

Pregunta:
{query}

Respuesta:
"""
    return prompt

In [7]:
prompt_preview = build_prompt(
    "¿Qué candidatos hablan de salud pública?",
    retrieve_chunks("salud pública, hospitales y atención primaria", top_k=4)
)

print(prompt_preview[:2500])

Eres un asistente analítico que responde preguntas sobre planes de gobierno presidenciales.
Usa únicamente el contexto proporcionado.
Si la respuesta no se encuentra claramente en el contexto, responde: "No lo sé con la evidencia recuperada".

Contexto:
[VLADIMIR ROY CERRON ROJAS | chunk 8] comunitario, familias y resueltas en el primer equipo de médicos generando altos comunidades, y nivel de atención de la familia a niveles de acción preventiva • tasa de cada territorio enfermedades sobre los hospitalizaciones por definido, evitables, determinantes enfermedades garantizando saturación sociales de la prevenibles cobertura hospitalaria y salud, fortaleciendo • prevalencia de progresiva de la mayores costos el primer nivel de anemia y desnutrición población. sociales y atención como eje infantil • lograr que la económicos para el del sistema público • número de visitas mayoría de estado y las de salud. domiciliarias atenciones de familias. preventivas realizadas salud se resuelvan en el primer nivel de atención, reduciendo la sobrecarga hospitalaria. • reducir de manera sostenida las hospitalizaciones por enfermedades prevenibles, mediante prevención y seguimiento comunitario. • disminuir significativamente la anemia y la desnutrición infantil, como resultado del enfoque preventivo, familiar y territorial. • institucionalizar la visita domiciliaria preventiva como práctica regular del sistema público de salud. 7. altos niveles de 7. reducir 7. • tasa de 7. • reducir la anemia, drásticamente la mortalidad materna por mortalidad materna

[VLADIMIR ROY CERRON ROJAS | chunk 6] • porcentaje de postergadas, al recursos en zonas estatal, establecimientos de 2031. urbanas garantizando el salud con • alcanzar como privilegiadas y derecho universal a equipamiento básico mínimo 3 camas excluido a amplios la salud, la completo y personal hospitalarias por sectores del país, formación y suficiente cada 1,000 vulnerando el especialización • brecha regional de habitantes en todas derecho a la salud permanente del infraestructura y las regiones del del pueblo, personal sanitario, recursos humanos en país al 2031. especialmente en y consolidando a salud (%) • lograr como regiones rurales, los hospitales mínimo 34 médicos amazónicas y de públicos como por cada 10,000 frontera. hospitales habitantes, con docentes, pilares distribución de un sistema de equitativa entre salud público, regiones al 2031. gratuito y de • garantizar que calidad. la mayoría de establecimientos de sa

# 6. Integración con un modelo generativo

Para docencia y pruebas locales, puedes usar modelos pequeños de Hugging Face.  
Dependiendo del entorno, algunos modelos pueden requerir más memoria.

## Opción docente liviana
- `google/flan-t5-base`

## Otras opciones
- modelos instruccionales pequeños
- APIs externas si el curso lo permite

In [9]:
from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="google/flan-t5-base"
)

model.safetensors:   0%|          | 0.00/990M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/282 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

The model 'T5ForConditionalGeneration' is not supported for text-generation. Supported models are ['PeftModelForCausalLM', 'AfmoeForCausalLM', 'ApertusForCausalLM', 'ArceeForCausalLM', 'AriaTextForCausalLM', 'BambaForCausalLM', 'BartForCausalLM', 'BertLMHeadModel', 'BertGenerationDecoder', 'BigBirdForCausalLM', 'BigBirdPegasusForCausalLM', 'BioGptForCausalLM', 'BitNetForCausalLM', 'BlenderbotForCausalLM', 'BlenderbotSmallForCausalLM', 'BloomForCausalLM', 'BltForCausalLM', 'CamembertForCausalLM', 'LlamaForCausalLM', 'CodeGenForCausalLM', 'CohereForCausalLM', 'Cohere2ForCausalLM', 'CpmAntForCausalLM', 'CTRLLMHeadModel', 'CwmForCausalLM', 'Data2VecTextForCausalLM', 'DbrxForCausalLM', 'DeepseekV2ForCausalLM', 'DeepseekV3ForCausalLM', 'DiffLlamaForCausalLM', 'DogeForCausalLM', 'Dots1ForCausalLM', 'ElectraForCausalLM', 'Emu3ForCausalLM', 'ErnieForCausalLM', 'Ernie4_5ForCausalLM', 'Ernie4_5_MoeForCausalLM', 'Exaone4ForCausalLM', 'ExaoneMoeForCausalLM', 'FalconForCausalLM', 'FalconH1ForCausalLM', 'FalconMambaForCausalLM', 'FlexOlmoForCausalLM', 'FuyuForCausalLM', 'GemmaForCausalLM', 'Gemma2ForCausalLM', 'Gemma3ForConditionalGeneration', 'Gemma3ForCausalLM', 'Gemma3nForConditionalGeneration', 'Gemma3nForCausalLM', 'GitForCausalLM', 'GlmForCausalLM', 'Glm4ForCausalLM', 'Glm4MoeForCausalLM', 'Glm4MoeLiteForCausalLM', 'GlmMoeDsaForCausalLM', 'GotOcr2ForConditionalGeneration', 'GPT2LMHeadModel', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTNeoForCausalLM', 'GPTNeoXForCausalLM', 'GPTNeoXJapaneseForCausalLM', 'GptOssForCausalLM', 'GPTJForCausalLM', 'GraniteForCausalLM', 'GraniteMoeForCausalLM', 'GraniteMoeHybridForCausalLM', 'GraniteMoeSharedForCausalLM', 'HeliumForCausalLM', 'HunYuanDenseV1ForCausalLM', 'HunYuanMoEV1ForCausalLM', 'Jais2ForCausalLM', 'JambaForCausalLM', 'JetMoeForCausalLM', 'Lfm2ForCausalLM', 'Lfm2MoeForCausalLM', 'LlamaForCausalLM', 'Llama4ForCausalLM', 'Llama4ForCausalLM', 'LongcatFlashForCausalLM', 'MambaForCausalLM', 'Mamba2ForCausalLM', 'MarianForCausalLM', 'MBartForCausalLM', 'MegatronBertForCausalLM', 'MiniMaxForCausalLM', 'MiniMaxM2ForCausalLM', 'MinistralForCausalLM', 'Ministral3ForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'MllamaForCausalLM', 'ModernBertDecoderForCausalLM', 'MoshiForCausalLM', 'MptForCausalLM', 'MusicgenForCausalLM', 'MusicgenMelodyForCausalLM', 'MvpForCausalLM', 'NanoChatForCausalLM', 'NemotronForCausalLM', 'NemotronHForCausalLM', 'OlmoForCausalLM', 'Olmo2ForCausalLM', 'Olmo3ForCausalLM', 'OlmoHybridForCausalLM', 'OlmoeForCausalLM', 'OpenAIGPTLMHeadModel', 'OPTForCausalLM', 'PegasusForCausalLM', 'PersimmonForCausalLM', 'PhiForCausalLM', 'Phi3ForCausalLM', 'Phi4MultimodalForCausalLM', 'PhimoeForCausalLM', 'PLBartForCausalLM', 'ProphetNetForCausalLM', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'Qwen3ForCausalLM', 'Qwen3_5ForCausalLM', 'Qwen3_5MoeForCausalLM', 'Qwen3_5MoeForCausalLM', 'Qwen3_5ForCausalLM', 'Qwen3MoeForCausalLM', 'Qwen3NextForCausalLM', 'RecurrentGemmaForCausalLM', 'ReformerModelWithLMHead', 'RemBertForCausalLM', 'RobertaForCausalLM', 'RobertaPreLayerNormForCausalLM', 'RoCBertForCausalLM', 'RoFormerForCausalLM', 'RwkvForCausalLM', 'SeedOssForCausalLM', 'SmolLM3ForCausalLM', 'SolarOpenForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'TrOCRForCausalLM', 'VaultGemmaForCausalLM', 'WhisperForCausalLM', 'XGLMForCausalLM', 'XLMWithLMHeadModel', 'XLMRobertaForCausalLM', 'XLMRobertaXLForCausalLM', 'XLNetLMHeadModel', 'xLSTMForCausalLM', 'XmodForCausalLM', 'YoutuForCausalLM', 'ZambaForCausalLM', 'Zamba2ForCausalLM'].

# 7. Función final del sistema RAG

In [10]:
def rag_answer(query, top_k=5, max_new_tokens=220):
    retrieved = retrieve_chunks(query, top_k=top_k)
    prompt = build_prompt(query, retrieved)
    response = generator(prompt, max_new_tokens=max_new_tokens)[0]["generated_text"]
    return {
        "query": query,
        "retrieved": retrieved,
        "prompt": prompt,
        "answer": response
    }

In [11]:
result = rag_answer("¿Qué candidatos mencionan educación pública y mejora de la calidad educativa?", top_k=4)
print(result["answer"])

Token indices sequence length is longer than the specified maximum sequence length for this model (2033 > 512). Running this sequence through the model will result in indexing errors
Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=220) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Eres un asistente analítico que responde preguntas sobre planes de gobierno presidenciales.
Usa únicamente el contexto proporcionado.
Si la respuesta no se encuentra claramente en el contexto, responde: "No lo sé con la evidencia recuperada".

Contexto:
[PABLO ALFONSO LOPEZ CHAU NAVA | chunk 7] abandono y baja educación de implemente estrategias conclusión de la calidad a lo largo orientadas a que la educación básica de la vida, con totalidad de los enfoque territorial, estudiantes de que desarrolle el educación primaria máximo potencial comprendan lo que de los estudiantes, lean asegure su tránsito a la educación superior y al trabajo, cierre brechas de exclusión y bajo rendimiento, y fortalezca a las instituciones educativas como espacios de transformación e innovación, con participación de estudiantes y familias 15. baja calidad, 15. garantizar una 15. garantizar que el 15. 1 acceso limitado, educación de sistema educativo abandono y baja calidad a lo largo implemente estrategias conclusión de la de la vida, con orientadas a que la educación básica enfoque territorial, totalidad de los que desarrolle el estudiantes de máximo potencial educación primaria de los estudiantes, logren la competencia asegure su tránsito de razonamiento a la educación matemático superior y al trabajo, cierre brechas de exclusión y bajo rendimiento, y fortalezca a las instituciones educativas como espacios de transformación e innovación, con participación de estudiantes y familias 16. baja

[ROBERTO HELBERT SANCHEZ PALOMINO | chunk 6] de vacantes en tecnólogos universidades médicos por cada públicas 10mil habitantes. disponibles en carreras ¿ % de plazas vinculadas a la serums alineadas medicina a prioridades humana. sanitarias nacionales. ¿ % del incremento del número de vacantes en universidades públicas destinadas al estudio de carreras vinculadas a la medicina humana. 2. 2 en materia de 2. 2 objetivos 2. 2 principales 2. 2 principales educación: estratégicos: indicadores: metas: ¿ mercantilización ¿ restituir el ¿ % del pbi ¿ analfabetismo del sistema educativo carácter público, destinado a cero. y debilitamiento de la universal, gratuito e educación. ¿ deserción < educación pública. intercultural del ¿ % de 2%. sistema educativo y matrícula pública ¿ 1 millón de ¿ déficit de fortalecer el rol del en educación estudiantes con infraestructura estado como superior. apoyo integral. educativa y garante del ¿ % de ¿ 90% de condiciones derecho a la reducción de docentes materiales indignas. educación. brecha nombrados. urbano–rural en ¿ 70% cierre de ¿ analfabetismo y ¿ cierre aprendizajes. brecha eib. deserción escolar progresivo de la ¿ % de brecha ¿ reducir la

[PABLO ALFONSO LOPEZ CHAU NAVA | chunk 6] la educación superior y al trabajo, cierre brechas de exclusión y bajo rendimiento, y fortalezca a las instituciones educativas como espacios de transformación e innovación, con participación de estudiantes y familias 13. baja calidad, 13. garantizar una 13. creación de un 13. 1 acceso limitado, educación de programa que elimine abandono y baja calidad a lo largo la deserción del conclusión de la de la vida, con sistema educativo en educación básica enfoque territorial, los estudiantes de que desarrolle el primaria y secundaria. máximo potencial de los estudiantes, asegure su tránsito a la educación superior y al trabajo, cierre brechas de exclusión y bajo rendimiento, y fortalezca a las instituciones educativas como espacios de transformación e innovación, con participación de estudiantes y familias 14. baja calidad, 14. 4.1. 14. garantizar que el 14. 1 acceso limitado, garantizar una sistema educativo abandono y baja educación de implemente estrategias conclusión de la calidad a lo largo orientadas a que la educación básica de la vida, con totalidad de los enfoque territorial, estudiantes de que desarrolle el educación primaria máximo potencial comprendan lo

[ROBERTO HELBERT SANCHEZ PALOMINO | chunk 14] disponibles en entre 15 a 29 años segunda entidades no estudian ni oportunidad, públicas. trabajan. dirigida a jóvenes ¿ limitado acceso de entre 22 a 29 a educación superior años. de calidad para los ¿ crear el jóvenes. el 58,7% de instituto nacional jóvenes no logró por la acceder a educación empleabilidad. superior. ¿ programa de ¿ insuficiente primeras prácticas implementación de la profesionales en el ley sobre sector público, a modalidades través del formativas incremento de laborales. plazas en los ¿ el 8,4% de diferentes niveles mujeres de gobierno. adolescentes son ¿ fortalecer la madres o han estado educación sexual embarazadas por integral (esi) a primera vez. desarrollarse en ¿ 6 de cada 10 toda la comunidad personas con educativa. discapacidad y en ¿ fortalecer el edad de trabajar, no sistema de salud tienen empleo. comunitario. ¿ implementar el programa de certificación y empleabilidad de para personas jóvenes con discapacidad. dimensión institucional 1. 1 retorno a la 1. 1 objetivos 1. 1 principales 1. 1 principales democracia y nueva estratégicos: indicadores: metas: constitución: ¿ mecanismos ¿ nueva ¿ crisis

Pregunta:
¿Qué candidatos mencionan educación pública y mejora de la calidad educativa?

Respuesta:

In [12]:
result["retrieved"][["presidente", "chunk_id", "distance_l2"]]

                           presidente  chunk_id  distance_l2
7       PABLO ALFONSO LOPEZ CHAU NAVA         7     0.590459
193  ROBERTO HELBERT SANCHEZ PALOMINO         6     0.603419
6       PABLO ALFONSO LOPEZ CHAU NAVA         6     0.643155
201  ROBERTO HELBERT SANCHEZ PALOMINO        14     0.648651

# 8. Casos de uso sobre el dataset real

Prueba preguntas como:

- ¿Qué candidatos hablan de salud pública?
- ¿Qué propuestas aparecen sobre telemedicina?
- ¿Qué candidatos mencionan minería y crecimiento económico?
- ¿Qué candidatos proponen mejoras en educación básica?
- ¿Qué evidencias concretas recupera el sistema?

Una buena práctica docente es comparar:
1. la respuesta final,
2. los chunks recuperados,
3. la trazabilidad hacia la evidencia.

In [13]:
preguntas_demo = [
    "¿Qué candidatos hablan de hospitales y salud pública?",
    "¿Qué candidatos mencionan telemedicina?",
    "¿Qué candidatos hablan de minería y exportaciones?",
    "¿Qué candidatos proponen mejoras en educación básica?"
]

for p in preguntas_demo:
    print("="*100)
    print("PREGUNTA:", p)
    out = rag_answer(p, top_k=4, max_new_tokens=180)
    print("RESPUESTA:", out["answer"])
    print()

====================================================================================================
PREGUNTA: ¿Qué candidatos hablan de hospitales y salud pública?

Both `max_new_tokens` (=180) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

RESPUESTA: Eres un asistente analítico que responde preguntas sobre planes de gobierno presidenciales.
Usa únicamente el contexto proporcionado.
Si la respuesta no se encuentra claramente en el contexto, responde: "No lo sé con la evidencia recuperada".

Contexto:
[VLADIMIR ROY CERRON ROJAS | chunk 8] comunitario, familias y resueltas en el primer equipo de médicos generando altos comunidades, y nivel de atención de la familia a niveles de acción preventiva • tasa de cada territorio enfermedades sobre los hospitalizaciones por definido, evitables, determinantes enfermedades garantizando saturación sociales de la prevenibles cobertura hospitalaria y salud, fortaleciendo • prevalencia de progresiva de la mayores costos el primer nivel de anemia y desnutrición población. sociales y atención como eje infantil • lograr que la económicos para el del sistema público • número de visitas mayoría de estado y las de salud. domiciliarias atenciones de familias. preventivas realizadas salud se resuelvan en el primer nivel de atención, reduciendo la sobrecarga hospitalaria. • reducir de manera sostenida las hospitalizaciones por enfermedades prevenibles, mediante prevención y seguimiento comunitario. • disminuir significativamente la anemia y la desnutrición infantil, como resultado del enfoque preventivo, familiar y territorial. • institucionalizar la visita domiciliaria preventiva como práctica regular del sistema público de salud. 7. altos niveles de 7. reducir 7. • tasa de 7. • reducir la anemia, drásticamente la mortalidad materna por mortalidad materna

[RONALD DARWIN ATENCIO SOTOMAYOR | chunk 11] 3: público cuando desarrollo de los estuvo enfermo. sistemas regionales • 45% de basados en la asegurados a atención primaria de essalud se atendió salud, con efectivas cuando estuvo redes integrales de enfermo. salud, con institutos de referencia macrorregional, a cargo de los gobiernos regionales y con participación de los gobiernos locales y con mecanismos efectivos de participación social. actividad estratégica 4: fortalecimiento y modernización, en todo el sistema público de salud, de la capacidad de gestión: hospitalaria; de la aps; de redes y de la referencia- contrarreferencia; del personal de salud; de las inversiones; de medicamentos; de la telemedicina. dimensión institucional 1. el congreso 1. objetivo 1. • ley derogada 1. • ley 31399 desnaturalizó el estratégico 1: quitar • ley modificada derogada. sentido del el cerrojo al • modificación de referéndum como referéndum (ley la ley n°26300 (vía expresión directa de 31399). facultades la soberanía y legislativas). dificultó procesos actividad constituyentes estratégica 1: desde la derogar la ley ciudadanía. en la 31399. práctica, monopolizó actividad el cambio estratégica 2: constitucional en el solicitar facultades parlamento. legislativas, para modificar

[VLADIMIR ROY CERRON ROJAS | chunk 6] • porcentaje de postergadas, al recursos en zonas estatal, establecimientos de 2031. urbanas garantizando el salud con • alcanzar como privilegiadas y derecho universal a equipamiento básico mínimo 3 camas excluido a amplios la salud, la completo y personal hospitalarias por sectores del país, formación y suficiente cada 1,000 vulnerando el especialización • brecha regional de habitantes en todas derecho a la salud permanente del infraestructura y las regiones del del pueblo, personal sanitario, recursos humanos en país al 2031. especialmente en y consolidando a salud (%) • lograr como regiones rurales, los hospitales mínimo 34 médicos amazónicas y de públicos como por cada 10,000 frontera. hospitales habitantes, con docentes, pilares distribución de un sistema de equitativa entre salud público, regiones al 2031. gratuito y de • garantizar que calidad. la mayoría de establecimientos de salud cuenten con equipamiento básico completo y personal suficiente, asegurando funcionamiento efectivo del primer y segundo nivel de atención. • reducir de manera sustantiva las brechas regionales en infraestructura y personal sanitario, priorizando zonas rurales, amazónicas y de frontera. 6. predominio de 6. implementar un

[KEIKO SOFIA FUJIMORI HIGUCHI | chunk 2] nivel y respuesta del coordinación de propio, mivivienda y reducir en 30% los estado. emergencias, así vivienda rural. tiempos de espera 2. el acceso limitado con patrulleros y hospitalaria. y tardío a consultas cámaras orientadas 3. asegurar y diagnósticos en el a reducir la viviendas sistema de salud, inseguridad y adecuadas para que afecta la calidad recuperar los 1.25 millones de de atención y el espacios tomados peruanos trato digno al por el crimen. vulnerables, paciente. 2. despliegue de un mediante programas 3. el déficit de sistema de habitacionales y vivienda digna y telemedicina reubicación de formal, con alta nacional para familias en zonas de informalidad y ampliar la cobertura riesgo. dificultades de de consultas y acceso, diagnósticos, así especialmente para como el jóvenes y familias otorgamiento de vulnerables. citas prontas en ambientes cómodos y adecuados, como medida prioritaria, garantizando trato digno al paciente. 3. desarrollo de un programa integral de vivienda digna que combine construcción masiva de viviendas, ampliación de techo propio, mivivienda, vivienda rural que incluya la compra de vivienda para jóvenes, así como la titulación digital masiva

Pregunta:
¿Qué candidatos hablan de hospitales y salud pública?

Respuesta:


====================================================================================================
PREGUNTA: ¿Qué candidatos mencionan telemedicina?

Both `max_new_tokens` (=180) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

RESPUESTA: Eres un asistente analítico que responde preguntas sobre planes de gobierno presidenciales.
Usa únicamente el contexto proporcionado.
Si la respuesta no se encuentra claramente en el contexto, responde: "No lo sé con la evidencia recuperada".

Contexto:
[MESIAS ANTONIO GUEVARA AMASIFUEN | chunk 2] 30 minutos. 4. centralización de 4. establecer cinco 4. número de 4. 5 la atención de casos macrorregiones con macrorregiones con médicos complejos hospitales de nivel hospitales de nivel únicamente en iv especializados. iv operativos. lima. 5. zonas rurales sin 5. implementar una 5. número de 5. 2,500 especialistas, red de telemedicina establecimientos atendidas solo por con 2,500 rurales con servicio médicos generales. establecimientos de telemedicina. rurales. 6. brecha digital en 6. desarrollar una 6. porcentaje de 6. 100% la educación, con un plataforma escuelas con 40% de escuelas sin educativa nacional conectividad internet funcional. con contenidos de funcional. ciencia, tecnología, ingeniería, artes y matemáticas (stem+h). 7. educación 7. equipar con 7. porcentaje de 7. 90% memorística laboratorios escuelas reflejada en el bajo stem+h todas las secundarias con puntaje de 374 en escuelas laboratorios matemáticas en la secundarias. equipados. última prueba pisa. 8. acceso limitado a 8. universalizar la 8. porcentaje de 8. 80% la educación inicial, educación inicial a niños de 0 a 5 años donde solo el 50% través de centros con acceso a de los niños de

[KEIKO SOFIA FUJIMORI HIGUCHI | chunk 2] nivel y respuesta del coordinación de propio, mivivienda y reducir en 30% los estado. emergencias, así vivienda rural. tiempos de espera 2. el acceso limitado con patrulleros y hospitalaria. y tardío a consultas cámaras orientadas 3. asegurar y diagnósticos en el a reducir la viviendas sistema de salud, inseguridad y adecuadas para que afecta la calidad recuperar los 1.25 millones de de atención y el espacios tomados peruanos trato digno al por el crimen. vulnerables, paciente. 2. despliegue de un mediante programas 3. el déficit de sistema de habitacionales y vivienda digna y telemedicina reubicación de formal, con alta nacional para familias en zonas de informalidad y ampliar la cobertura riesgo. dificultades de de consultas y acceso, diagnósticos, así especialmente para como el jóvenes y familias otorgamiento de vulnerables. citas prontas en ambientes cómodos y adecuados, como medida prioritaria, garantizando trato digno al paciente. 3. desarrollo de un programa integral de vivienda digna que combine construcción masiva de viviendas, ampliación de techo propio, mivivienda, vivienda rural que incluya la compra de vivienda para jóvenes, así como la titulación digital masiva

[ANTONIO ORTIZ VILLANO | chunk 20] al menos el telesalud consiste ciudadana de forma actualmente se 40% de las en atender a un preventiva en presentan son preventivas atenciones que paciente los temas de salud para controlar actualmente se en cualquier lugar, para controlar enfermedades y epidemias presentan son sin tener al enfermedades y % de las atenciones que preventivas especialista en epidemias actualmente generan para controlar persona, usando la fortaleciendo y derivaciones presenciales enfermedades y tecnología actual ampliando el uso innecesarias por epidemias. para verse de la teleiec telesalud, contribuyendo a la resolver al por video. telesalud con descentralización menos el 40% de el perú cuenta con la comunidad. del sistema de salud. las atenciones una red de fibra fortalecer y % de establecimientos de que actualmente óptica adaptar los salud que integraron o generan nacional que puede sistemas de salud iniciaron actividades en la derivaciones soportar la para red nacional de salud presenciales velocidad de la implementación digital innecesarias por internet requerida de la telesalud en telesalud, para tener las 25 contribuyendo a telemedicina en regiones, de su la zonas alejadas del dinámica, procesos,

[ANTONIO ORTIZ VILLANO | chunk 21] derivaciones soportar la para red nacional de salud presenciales velocidad de la implementación digital innecesarias por internet requerida de la telesalud en telesalud, para tener las 25 contribuyendo a telemedicina en regiones, de su la zonas alejadas del dinámica, procesos, descentralización país. formalización del según minsa, en institucional de las sistema de salud un año se pueden “tele 40% de gastar especialidades” por establecimientos alrededor de s/. 400 ejemplo de salud que millones de soles en telepediatría , integraron o pagos teleoncología , etc.; iniciaron de viáticos y dietas y la consecución de actividades en la a pacientes su red derivados a propio pliego como nacional de lima. el 60% de servicio de salud. salud digital estos gastos se pudo haber evitado de haberse tratado a pacientes de manera local. 13. brecha digital 13. apoyo 13. % de la población 13. al menos el en los servicios de en la usuaria del sistema público 40% de la salud. implementación del de población usuaria las historias “plan de salud cuya atención se del clínicas del sector implementación del registra en una

Pregunta:
¿Qué candidatos mencionan telemedicina?

Respuesta:


====================================================================================================
PREGUNTA: ¿Qué candidatos hablan de minería y exportaciones?
RESPUESTA: Eres un asistente analítico que responde preguntas sobre planes de gobierno presidenciales.
Usa únicamente el contexto proporcionado.
Si la respuesta no se encuentra claramente en el contexto, responde: "No lo sé con la evidencia recuperada".

Contexto:
[RICARDO PABLO BELMONT CASSINELLI | chunk 16] nivel de productos centros de acopio construidos o nacional. ii) locales como agro, municipales' a reactivados. b) incrementar en un acuicultura y escala adecuada. incremento en el 20% el valor de artesanía. valor de las exportaciones exportaciones de regionales con valor productos con valor agregado. iii) agregado de generar 10,000 regiones fuera de empleos directos en lima. c) número de estas instalaciones. puestos de trabajo directos creados. 5. mas de 200 años 5. industrializar la 5. el porcentaje de 5. industrializar la exportando materia minería y exportar exportación minera minería , invitando a primas. productos como materia prima empresas terminados. es muy alto, extranjeras a traer representando más tecnología e invertir del 60% de las en el perú. exportaciones totales en países como perú, con el cobre liderando (cerca del 30-50% de las mineras), seguido por oro, zinc y hierro dimensión territorial - ambiental 1. crecimiento 1. impulsar y 1. a) número de 1. i) actualizar y urbano financiar la municipios con aprobar los planes desordenado y falta actualización de planes de en 150 de planificación planes de ordenamiento municipalidades

[FRANCISCO ERNESTO DIEZ-CANSECO TÁVARA | chunk 12] 14 proyectos). detener zonas pluviales y con toda la número de mineros progresivamente cabeceras de ríos. capacidad policial y ilegales capturados operaciones de la deforestación en militar. convertir a y procesados. petroperú en la la amazonía perú en potencia de número de selva; implementar relacionada a tala exportación concesiones ley que obligue a ilegal, minería ilegal agroindustrial mineras ociosas concesionarios y construcción de mediante recuperadas por el mineros a operar en pistas de aterrizaje construcción de 14 estado. 1 año o devolver ilegales contribuye a proyectos de número de concesiones al la pérdida de irrigación y empresas mineras estado; asociar biodiversidad. flotas represas. formales creadas mineros reinfo en pesqueras reestructurar por asociación de grandes empresas extranjeras integralmente mineros reinfo. formales; erradicar depredan especies petroperú número de 100% de minería marinas en el litoral otorgándole operativos navales ilegal en reservas peruano usando gobernanza privada contra pesca ilegal naturales, métodos prohibidos. y buscar alianza con de flotas cabeceras de ríos y los incendios chevron para extranjeras. zonas prohibidas forestales convertirla en número de focos de mediante provocados en empresa público- incendios forestales

[ROBERTO HELBERT SANCHEZ PALOMINO | chunk 30] la comunales medios de cadena de valor mineras, producción por los controlada por el establecidas y posesionarios de las estado. funcionando en concesiones de parques mineros. extracción y de ¿ % de parques ¿ 70% de beneficio y el mineros, con concesiones en desarrollo de planes de conflicto capitales desarrollo formalizadas a (apropiación de sostenible del favor de las plusvalía) basados territorio. cooperativas en la explotación de mineras y miles de mineros. ¿ % de parque comunidades ¿ el 90% de los mineros que campesinas. mineros en proceso cuentan con ¿ 60% del oro de formalización no servicios básicos, producido en los son propietarios de servicios de salud parques mineros las concesiones y educación. por las donde operan. cooperativas ¿ el trabajo de mineras es niños y mujeres comercializado a pallaqueras través del estado. constituye un alto grado de explotación. ¿ 100% del flujo ¿ la minería ilegal de insumos es e informal ha sido controlado por el responsable de la estado. deforestación de ¿ 100% del grandes extensiones proceso de de selva y la producción de las contaminación de

[ROBERTO HELBERT SANCHEZ PALOMINO | chunk 28] y educación precarios, cooperativas productividad. lo que ha estimulado agropecuarias. ¿ 500 mil has la migración de los ¿ % de poblados de nuevas jóvenes que no rurales con planes irrigaciones tienen oportunidad en de desarrollo implementadas. el desarrollo agrario. sostenible. ¿ 50% de poblados rurales tiene planes de desarrollo territorial implementados. 4. 4 en materia de 4. 4 objetivos 4. 4 principales 4. 4 principales la pequeña minería estratégicos: indicadores: metas: informal y artesanal: ¿ establecer la ¿ % de mineros ¿ 100% de las ¿ entre 300 mil a propiedad social de artesanales e concesiones 500 mil personas se los medios de informales extinguidas pasan dedican a la minería producción en la asociados en al control del informal y artesanal. pequeña minería y cooperativas y estado. ¿ de los 86 mil minería artesanal a produciendo en ¿ reducción del mineros inscritos en través de parques mineros. tiempo de las el reinfo, solo 2500 cooperativas. concesiones de han logrado ¿ % de 30 a 5 años. completar el proceso ¿ controlar la concesiones ¿ 70% de en los últimos

Pregunta:
¿Qué candidatos hablan de minería y exportaciones?

Respuesta:


====================================================================================================
PREGUNTA: ¿Qué candidatos proponen mejoras en educación básica?

Both `max_new_tokens` (=180) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

RESPUESTA: Eres un asistente analítico que responde preguntas sobre planes de gobierno presidenciales.
Usa únicamente el contexto proporcionado.
Si la respuesta no se encuentra claramente en el contexto, responde: "No lo sé con la evidencia recuperada".

Contexto:
[ANTONIO ORTIZ VILLANO | chunk 14] según una 7. fomentar el 7. % de padres y madres de 7. reducir al 40 encuesta realizada involucramiento de familia que participan % la proporción por la los padres en activamente en al menos de padres con organización la educación de sus una actividad bajo o nulo "ciudadanos al día" hijos, como la educativa escolar anual involucramiento, en el 2019, el creación de logrando que al 67% de los padres programas de menos el 60 % en el perú se capacitación para de los padres involucran poco padres y la participe o nada en la implementación de activamente en la educación de sus plataformas educación de sus hijos (garcía, virtuales para hijos. 2019). esto se debe mejorar la en parte a la falta de comunicación entre tiempo debido a la padres y carga laboral y la docentes (minedu, falta de 2020). comprensión de la importancia del involucramiento de los padres en la educación de sus hijos. 8. según el plan de 8. asegurar 8. % de iiee con 8. cierre de infraestructura condiciones condiciones básicas de brecha en educativa

[ROBERTO HELBERT SANCHEZ PALOMINO | chunk 8] docentes ¿ incrementar ¿ 58% de niños, nombrados. 50% la inversión niñas y adolescentes ¿ garantizar la ¿ % de docentes por estudiante con discapacidad estabilidad laboral, con formación en universitario están fuera del la formación de eib. respecto a línea sistema educativo. calidad y salarios ¿ cobertura de base. dignos para las y educación ¿ triplicar el ¿ precarización los docentes. intercultural número de laboral docente y bilingüe (eib), docentes a brechas de ¿ construir un especialmente en tiempo completo. formación. sistema educativo secundaria. ¿ alcanzar inclusivo, libre de ¿ % de 0.5% del pbi en ¿ brechas de violencia y estudiantes con investigación, género, respetuoso de las discapacidad que ciencia y discapacidad, identidades. reciben apoyos y tecnología. interculturalidad y servicios. ¿ 70% de territoriales. ¿ reforzar el ¿ presupuesto universidades sistema anual promedio públicas con ¿ crisis estructural universitario público por estudiante condiciones de en la universidad con financiamiento universitario calidad pública. adecuado para el ¿ % de docentes reforzadas / fortalecimiento de universitarios a acreditación. ¿ regulación la plana docente y tiempo completo ¿ alcanzar universitaria sin

[ROBERTO HELBERT SANCHEZ PALOMINO | chunk 6] de vacantes en tecnólogos universidades médicos por cada públicas 10mil habitantes. disponibles en carreras ¿ % de plazas vinculadas a la serums alineadas medicina a prioridades humana. sanitarias nacionales. ¿ % del incremento del número de vacantes en universidades públicas destinadas al estudio de carreras vinculadas a la medicina humana. 2. 2 en materia de 2. 2 objetivos 2. 2 principales 2. 2 principales educación: estratégicos: indicadores: metas: ¿ mercantilización ¿ restituir el ¿ % del pbi ¿ analfabetismo del sistema educativo carácter público, destinado a cero. y debilitamiento de la universal, gratuito e educación. ¿ deserción < educación pública. intercultural del ¿ % de 2%. sistema educativo y matrícula pública ¿ 1 millón de ¿ déficit de fortalecer el rol del en educación estudiantes con infraestructura estado como superior. apoyo integral. educativa y garante del ¿ % de ¿ 90% de condiciones derecho a la reducción de docentes materiales indignas. educación. brecha nombrados. urbano–rural en ¿ 70% cierre de ¿ analfabetismo y ¿ cierre aprendizajes. brecha eib. deserción escolar progresivo de la ¿ % de brecha ¿ reducir la

[PABLO ALFONSO LOPEZ CHAU NAVA | chunk 6] la educación superior y al trabajo, cierre brechas de exclusión y bajo rendimiento, y fortalezca a las instituciones educativas como espacios de transformación e innovación, con participación de estudiantes y familias 13. baja calidad, 13. garantizar una 13. creación de un 13. 1 acceso limitado, educación de programa que elimine abandono y baja calidad a lo largo la deserción del conclusión de la de la vida, con sistema educativo en educación básica enfoque territorial, los estudiantes de que desarrolle el primaria y secundaria. máximo potencial de los estudiantes, asegure su tránsito a la educación superior y al trabajo, cierre brechas de exclusión y bajo rendimiento, y fortalezca a las instituciones educativas como espacios de transformación e innovación, con participación de estudiantes y familias 14. baja calidad, 14. 4.1. 14. garantizar que el 14. 1 acceso limitado, garantizar una sistema educativo abandono y baja educación de implemente estrategias conclusión de la calidad a lo largo orientadas a que la educación básica de la vida, con totalidad de los enfoque territorial, estudiantes de que desarrolle el educación primaria máximo potencial comprendan lo

Pregunta:
¿Qué candidatos proponen mejoras en educación básica?

Respuesta:

# 9. Evaluación cualitativa del sistema

Al evaluar un mini chatbot con RAG no basta con leer la respuesta final.  
Debemos revisar:

1. **Retrieval**: ¿recuperó evidencia pertinente?
2. **Grounding**: ¿la respuesta está soportada por el contexto?
3. **Cobertura**: ¿faltó información importante?
4. **Faithfulness**: ¿inventó algo no presente?
5. **Claridad**: ¿respondió de forma útil?

## Posibles mejoras
- reranking
- chunking semántico por párrafos
- filtros por candidato
- ranking híbrido TF-IDF + embeddings
- modelos generativos más fuertes

# 10. Cierre de la masterclass

Con esta clase cerramos el bloque moderno de NLP aplicado:

- En la clase 14A representamos texto con embeddings.
- En la clase 14B construimos retrieval semántico con chunks y FAISS.
- En la clase 14C integramos todo en un mini sistema conversacional con RAG.

## Frase final
**El verdadero valor de un sistema de IA aplicada no está solo en generar texto, sino en generar respuestas sustentadas por evidencia recuperada.**